[package]
name = "dream"
version = "0.0.0"
authors = ["silentdoer <1010993610@qq.com>"]
edition = "2018"
license = "MIT"
description = "simple rpc."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
